blog/urls.py
from django.urls import path
from blog import views
from blog.feeds import LatestPostsFeed

# define app namespace to use in URLs when calling
app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),  # using a function
    # path("", views.PostListView.as_view(), name="post_list"),  # using a class
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    # use slug path converter to match param as lowercase string with ASCII plus hyphen and underscores
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

publisher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("home/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    """
    Stores a single post .related to :model: `auth.User`
    """

    STATUS_CHOICES = (("draft", "Draft"), ("published", "Published"))
    title = models.CharField(max_length=250)
    # only one post with a slug for a given date
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    objects = models.Manager()  # default manager
    published = PublishedManager()  # custom manager
    tags = TaggableManager()

    class Meta:
        # recent posts appear first
        ordering = ("-publish",)
        # Todo: come back to see how
        # default_manager_name = PublishedManager

        def __str__(self):
            return self.title

    def get_absolute_url(self):
        """Access the full URL of a single post"""
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comments(models.Model):
    """Shows the views on a specific post. Relates to :model: `blog.Post`"""

    # let me get the comment of a post via comment.post or all comments of a post via post.comments.all()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    #  name of the user who created the comment
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from blog.models import Comments


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ("name", "email", "body")


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from taggit.models import Tag
from blog.forms import EmailPostForm, CommentForm, SearchForm
from blog.models import Post, Comments

# class PostListView(ListView):
#     # alternative syntax to get all posts instead of just published posts
#     # model = Post
#     queryset = Post.published.all()
#     # default without specification is object_list
#     # ? is this equivalent to post_list
#     context_object_name = "posts"
#     paginate_by = 3
#     # default without specification is blog/post_list.html
#     template_name = "blog/post/list.html"


def post_list(request, tag_slug=None):
    """
    Display a list of published posts

    **Context**
    ``Post``
        An instance of :model:`blog.Post`

    **Template:**
      :template:`blog/post/list.html`
    """
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 posts per paeg
    page = request.GET.get("page")

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # deliver the first page if the page is not an integer
        posts = paginator.page(1)
    except EmptyPage:
        # give the last page if the page is out of bounds
        posts = paginator.page(paginator.num_pages)

    return render(
        request, "blog/post/list.html", {"page": page, "posts": posts, "tag": tag}
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # create comment obj without saving to db
            new_comment = comment_form.save(commit=False)
            new_comment.post = post  # associate comment with post
            new_comment.save()  # eventually save
    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )


def post_share(request, post_id):
    # get post by id
    post = get_object_or_404(Post, id=post_id, status="published")
    sent = False
    form = EmailPostForm()
    if request.method == "POST":
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            # use get_absolute_url to build the complete URL including schema and host name
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{clean_data['name']} recommends you read {post.title}"
            from_email = "admin@publisher.com"
            message = f"Read {post.title} at {post_url} \n\n {clean_data['name']}'s comments: {clean_data['comments']}"
            # send mail
            send_mail(subject, message, from_email, [clean_data["to"]])
            sent = True

    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            #  perform a serch but order results by how many words of the query are contained in the object
            query = form.cleaned_data["query"]
            # let results contained in title prevail. values from A - D
            search_vector = SearchVector("title", weight="A") + SearchVector(
                "body", weight="B"
            )
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    search=search_vector, rank=SearchRank(search_vector, search_query)
                )
                .filter(rank__gte=0.3)
                .order_by("-rank")
            )
    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
<!-- locate blog_tags.py -->
{% load blog_tags %}
{% block title%} {{post.title}} {% endblock %}

{% block content %}


<h1>{{post.title}}</h1>
<p class="date"> Published {{post.publish}} by {{post.author}}</p>
{{post.body|markdown}}
<p>
    <!-- use app namespace blog and url named post_share -->
    <a href="{% url "blog:post_share" post.id %}"> Share this post</a>
</p>

<!--  assign a value to a variable until endwith -->
{% with comments.count as total_comments %}
<h2>
    {{total_comments}} comment{{ total_comments | pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.coutner }} by {{comment.name }}
            {{comment.created }}

        </p>
        {{ comment.body | linebreaks}}
    </div>
{% empty %}
    <p>
        There are no comments yet.
    </p>

{% endfor %}

  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{post.title}}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
<!--  inherit from base.html -->
{% extends "blog/base.html" %}

<!-- locate blog_tags.py -->
{% load blog_tags %}

{% block title %}Publisher{% endblock %}
{% block content %}
<h1>
    <a href="{% url "blog:post_list" %}">Publisher</a>
</h1>

{% if tag %}
<h2>Posts tagged with "{{tag.name}}"</h2>
{% endif %}
{% for post in posts %}
<h2><a href="{{post.get_absolute_url}}" class="text-capitalize">{{post.title}}</a></h2>
<p class="tags">Tags:
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{tag.name}}</a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}

</p>
<p class="date"> Published {{post.publish }} by {{post.author}}</p>
{{post.body|markdown|truncatewords_html:50}}
{% endfor %}
<!-- using function-based view -->
{% include "pagination.html" with page=posts %}
<!-- using a class-based view -->
<!-- {% include "pagination.html" with page=page_obj %} -->
{% endblock %}

blog/templates/blog/post/most_commented.html
<ul>
    {% for post in most_commented %}
    <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
    {% endfor%}
</ul>

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}
{% block content %}
    {% if query %}
        <h1>Posts containing "{{query}}"</h1>
        <h3>
            {% with results.count as total_results %}
            Found {{total_results}} result{{total_results| pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{post.get_absolute_url }}">{{post.title}}</a></h4>
            {{post.body|markdown|truncatewords_html:5}}
            {% empty %}
            <p>There are no results for your query.</p>
        {%endfor%}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>

    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{form.cleaned_data.to}}
        </p>
    {% else %}
        <h1>
            Share "{{post.title}}" by e-mail
        </h1>
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send e-mail" id=""></form>
    {% endif %}




{% endblock %}